Engine_Structs.h:
  CameraCacheEntry: # class name
    FCameraCacheEntry.FMinimalViewInfo: POV  # Will create an offset with the key "FCameraCacheEntry.FMinimalViewInfo"

Engine_Classes.h:
  Actor:
    AActor.rootComponent: RootComponent
  PlayerState:
    APlayerState.PlayerName: PlayerName
  GameInstance:
    _prefix: UGameInstance.  # _prefix allows you to shorten each entry inside this class
    1: LocalPlayers  # Will create an offset with the key "UGameInstance.LocalPlayers" (prefix + name of class field)
  Player:
    _prefix: ULocalPlayer.
    1: PlayerController  # "ULocalPlayer.PlayerController"
  World:
    _prefix: UWorld.  # _prefix will allow less copy-paste
    1: OwningGameInstance  # "UWorld.OwningGameInstance"
    2: PersistentLevel  # "UWorld.PersistentLevel"
  PlayerController:
    APlayerController.CameraManager: PlayerCameraManager
  PlayerCameraManager:
    APlayerCameraManager.CameraCache: CameraCache  # using a _prefix is optional