// Generated by DougTheDruid#2784 on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x0 (Full Size[0x28] - InheritedSize[0x28]
class AthenaServerMigrationGameAuthorityProviderInterface: public Interface
{
public:
};


// Size 0x0 (Full Size[0x28] - InheritedSize[0x28]
class MigrationProgressInterface: public Interface
{
public:
};


// Size 0x0 (Full Size[0x28] - InheritedSize[0x28]
class MigrationServiceInterface: public Interface
{
public:
};


// Size 0x0 (Full Size[0x28] - InheritedSize[0x28]
class ServerMigrationGatherableActorInterface: public Interface
{
public:
};


// Size 0x20 (Full Size[0xe8] - InheritedSize[0xc8]
class RegisterServerMigrationPointOfInterestComponent: public ActorComponent
{
public:
	float                                                        MigrationRadius;                                   // 0xc8(0x4)
	char                                                         pad0x1c_KCJR6[0x1c];                               // 0xcc(0x1c)
};


}