// Generated by DougTheDruid#2784 on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x18 (Full Size[0x830] - InheritedSize[0x818]
class BP_AIProjectile_SirenTrident_C: public SirenTridentProjectile
{
public:
	Class SphereCollisionExtentAdjustOverTimeComponent*          SphereCollisionExtentAdjustOverTime;               // 0x818(0x8)
	Class StaticMeshComponent*                                   Sphere;                                            // 0x820(0x8)
	Class SphereComponent*                                       Collision;                                         // 0x828(0x8)
};


}