// Generated by dougthedruid on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x30 (Full Size[0xb50] - InheritedSize[0xb20]
class BP_Blunderbuss_C: public ProjectileWeapon
{
public:
	Struct PointerToUberGraphFrame                               UberGraphFrame;                                    // 0xb20(0x8)
	Class PostProcessComponent*                                  PostProcess;                                       // 0xb28(0x8)
	byte                                                         sfx relationship;                                  // 0xb30(0x1)
	char                                                         pad0x7_8Y1XJ[0x7];                                 // 0xb31(0x7)
	Class MaterialInstanceDynamic*                               DynamicMaterial;                                   // 0xb38(0x8)
	Class Object*                                                FiringVFX3rdPerson;                                // 0xb40(0x8)
	Class WwiseEvent*                                            Blunderbuss Firing sfx 3rd person;                 // 0xb48(0x8)
};


}