// Generated by DougTheDruid#2784 on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x18
class BP_CaptainsLog_Wieldable_C: public CaptainsLogbookWieldable
{
public:
	Struct PointerToUberGraphFrame                               None;                                              // 0xc70(0x8)
	Class AnimNotifyWwiseEmitterComponent*                       None;                                              // 0xc78(0x8)
	Class SkeletalStashedMeshMemoryConstraintComponent*          None;                                              // 0xc80(0x8)
};


}