// Generated by DougTheDruid#2784 on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x18
class BP_Cannon_C: public Cannon
{
public:
	Class GroupedInteractableAreaComponent*                      GroupedInteractableArea;                           // 0xc90(0x8)
	Class InteractableComponent*                                 Interactable;                                      // 0xc98(0x8)
	Class StaticMeshComponent*                                   Collision;                                         // 0xca0(0x8)
};


}