// Generated by DougTheDruid#2784 on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x28 (Full Size[0x7c8] - InheritedSize[0x7a0]
class BP_Firework_Wieldable_C: public StaticMeshWieldableItem
{
public:
	Class UsableWieldableComponent*                              UsableWieldable;                                   // 0x7a0(0x8)
	Class WieldableInteractableComponent*                        WieldableInteractable;                             // 0x7a8(0x8)
	Class PickupableComponent*                                   Pickupable;                                        // 0x7b0(0x8)
	Class ConsumableWieldableComponent*                          ConsumableWieldable;                               // 0x7b8(0x8)
	Class InventoryItemComponent*                                InventoryItem;                                     // 0x7c0(0x8)
};


}