// Generated by dougthedruid on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x44b8f2e3 (Full Size[0x44b8f2e3] - InheritedSize[0x0]
class BP_FeatureIslandSunkenChestsSpawner_DVR_C: public None
{
public:
	char                                                         pad0x44b8f2e3_70WBC[0x44b8f2e3];                   // 0x0(0x44b8f2e3)
};


}