// Generated by dougthedruid on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x10 (Full Size[0x578] - InheritedSize[0x568]
class BP_ForceSpot_Rowboat_Launch_C: public ForceSpot
{
public:
	TArray<struct InteractionSplinePoints>                       InteractionSplinePoints;                           // 0x568(0x10)
};


}