// Generated by DougTheDruid#2784 on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x28
class BP_GoldhoarderShady_C: public CompanyShopkeeper
{
public:
	Struct PointerToUberGraphFrame                               None;                                              // 0x698(0x8)
	Class CapsuleComponent*                                      None;                                              // 0x6a0(0x8)
	Class NPCDialogComponent*                                    None;                                              // 0x6a8(0x8)
	Class StaticMeshComponent*                                   None;                                              // 0x6b0(0x8)
	byte                                                         ByteProperty;                                      // 0x0(0x0)
};


}