// Generated by DougTheDruid#2784 on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x0
class BP_gmp_pocketwatch_smp_01_a_ItemDesc_C: public ItemDesc
{
public:
};


// Size 0x0
class BP_gmp_pocket_watch_pio_01_a_ItemDesc_C: public ItemDesc
{
public:
};


// Size 0x0
class BP_gmp_pocket_watch_s06_01_a_ItemDesc_C: public ItemDesc
{
public:
};


// Size 0x0
class BP_gmp_pocket_watch_hwm_01_a_v02_ItemDesc_C: public ItemDesc
{
public:
};


}