// Generated by DougTheDruid#2784 on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x18 (Full Size[0xc38] - InheritedSize[0xc20]
class BP_HarpoonLauncher_C: public HarpoonLauncher
{
public:
	Class StaticMeshComponent*                                   CubeNotWalkable;                                   // 0xc20(0x8)
	Class CapsuleComponent*                                      MountCollision;                                    // 0xc28(0x8)
	Class CapsuleComponent*                                      BarrelCollision;                                   // 0xc30(0x8)
};


}