// Generated by DougTheDruid#2784 on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x20
class BP_Invisible_OpenDoor_MechanismTrigger_C: public SwitchMechanismTrigger
{
public:
	Class ArrowComponent*                                        Arrow;                                             // 0x560(0x8)
	Class InteractableComponent*                                 Interactable;                                      // 0x568(0x8)
	Class StaticMeshComponent*                                   LeverMesh;                                         // 0x570(0x8)
	Class StaticMeshComponent*                                   BaseMesh;                                          // 0x578(0x8)
};


}