// Generated by DougTheDruid#2784 on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x18 (Full Size[0xa50] - InheritedSize[0xa38]
class BP_large_mast_fore_C: public BP_Mast_C
{
public:
	Struct PointerToUberGraphFrame                               UberGraphFrame;                                    // 0xa38(0x8)
	Class StaticMeshComponent*                                   shp_flag_pennant_pole_01_a;                        // 0xa40(0x8)
	Class StaticMeshComponent*                                   shp_flag_pennant_01_a;                             // 0xa48(0x8)
};


}