// Generated by dougthedruid on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x20 (Full Size[0x6f8] - InheritedSize[0x6d8]
class BP_NPC_ReapersBones_Skeleton_InCage_C: public CompanyShopkeeper
{
public:
	Class CameraComponent*                                       NPCDialogCamera;                                   // 0x6d8(0x8)
	Class NPCDialogComponent*                                    NPCDialog;                                         // 0x6e0(0x8)
	Class AnimNotifyWwiseEmitterComponent*                       AnimNotifyWwiseEmitter;                            // 0x6e8(0x8)
	Class CapsuleComponent*                                      SolidHits;                                         // 0x6f0(0x8)
};


}