// Generated by dougthedruid on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x8 (Full Size[0x1828] - InheritedSize[0x1820]
class BP_OnlineAthenaPlayerController_C: public OnlineAthenaPlayerController
{
public:
	blueprintgeneratedclass BP_Component_Tutorial2019_C*         VisitShopkeepersTutorialComponent;                 // 0x1820(0x8)
};


}