// Generated by DougTheDruid#2784 on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x18 (Full Size[0x668] - InheritedSize[0x650]
class BP_Projectile_CannonBall_C: public CannonProjectile
{
public:
	Class SphereCollisionExtentAdjustOverTimeComponent*          SphereCollisionExtentAdjustOverTime;               // 0x650(0x8)
	Class StaticMeshComponent*                                   CannonBall;                                        // 0x658(0x8)
	Class SphereComponent*                                       Collision;                                         // 0x660(0x8)
};


}