#pragma once

// Generated by dougthedruid on Discord
// https://github.com/DougTheDruid

// Size 0x18 (Full Size[0x6e8] - InheritedSize[0x6d0]
class BP_Projectile_VolcanoRockSmall_C: public VolcanicRock
{
public:
	class RotatingAudioSourceComponent*                          RotatingAudioSource;                               // 0x6d0(0x8)
	class StaticMeshComponent*                                   RockMesh;                                          // 0x6d8(0x8)
	class SphereComponent*                                       Collision;                                         // 0x6e0(0x8)
};


