// Generated by DougTheDruid#2784 on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x10 (Full Size[0x3d8] - InheritedSize[0x3c8]
class BP_Premium_SpawnProxy_C: public Actor
{
public:
	Class PhasedActorComponent*                                  PhasedActor;                                       // 0x3c8(0x8)
	Class SceneComponent*                                        DefaultSceneRoot;                                  // 0x3d0(0x8)
};


}