// Generated by dougthedruid on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x8 (Full Size[0x420] - InheritedSize[0x418]
class BP_ReaperBountyBeacon_C: public MovingWorldMarkerBeaconActor
{
public:
	Class ParticleSystemComponent*                               None;                                              // 0x418(0x8)
};


}