// Generated by dougthedruid on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x11 (Full Size[0x11] - InheritedSize[0x0]
class BP_ResourceIslandWashedUpBountySkullsSpawner_DVR_C: public None
{
public:
	char                                                         pad0x11_KBGBY[0x11];                               // 0x0(0x11)
};


}