// Generated by DougTheDruid#2784 on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x18
class BP_SmallShip_StandardHull_InternalShipWater_C: public ShipInternalWater
{
public:
	Struct PointerToUberGraphFrame                               None;                                              // 0x620(0x8)
	Class DynamicFlowComponent*                                  None;                                              // 0x628(0x8)
	Class CurveFloat*                                            None;                                              // 0x630(0x8)
};


}