// Generated by dougthedruid on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x8 (Full Size[0x520] - InheritedSize[0x518]
class BP_ShipCustomizationChestInteraction_C: public ShipCustomizationChestInteraction
{
public:
	Class SceneComponent*                                        DefaultSceneRoot;                                  // 0x518(0x8)
};


}