// Generated by dougthedruid on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x30 (Full Size[0x5a0] - InheritedSize[0x570]
class BP_Soveriegn_LiftMechanism_Toggle_C: public ToggleAnimatedMechanismAction
{
public:
	struct PointerToUberGraphFrame                               UberGraphFrame;                                    // 0x570(0x8)
	class SceneComponent*                                        Rope Anchor Point;                                 // 0x578(0x8)
	class StaticMeshComponent*                                   StaticMesh4;                                       // 0x580(0x8)
	blueprintgeneratedclass BP_RopeRendererComponent_C*          BP_RopeRendererComponent;                          // 0x588(0x8)
	class SceneComponent*                                        Rope Source;                                       // 0x590(0x8)
	class IntentCombinerComponent*                               IntentCombiner;                                    // 0x598(0x8)
};


}