// Generated by DougTheDruid#2784 on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x8 (Full Size[0x730] - InheritedSize[0x728]
class BP_SmallShipStorageBarrel_Wood_C: public BootyItemInfo
{
public:
	Class SceneComponent*                                        DefaultSceneRoot;                                  // 0x728(0x8)
};


}