// Generated by dougthedruid on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x28 (Full Size[0x8b8] - InheritedSize[0x890]
class BP_StaticWieldableIngestible_C: public StaticWieldableIngestible
{
public:
	class MaterialManipulationComponent*                         MaterialManipulation;                              // 0x890(0x8)
	class PottableComponent*                                     Pottable;                                          // 0x898(0x8)
	class WieldableInteractableComponent*                        WieldableInteractable;                             // 0x8a0(0x8)
	class UsableWieldableComponent*                              UsableWieldable;                                   // 0x8a8(0x8)
	class PickupableComponent*                                   Pickupable;                                        // 0x8b0(0x8)
};


}