#pragma once

// Generated by dougthedruid on Discord
// https://github.com/DougTheDruid

// Size 0x8 (Full Size[0x480] - InheritedSize[0x478]
class BP_ShipPawn_C: public ShipProxyPawn
{
public:
	class SceneComponent*                                        DefaultSceneRoot;                                  // 0x478(0x8)
};


