// Generated by DougTheDruid#2784 on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x10
class BP_Trinket_KrakenEye_01_c_C: public BP_Trinket_StandingSmall_C
{
public:
	Class StaticMeshComponent*                                   cap_desk_model_kra_01_a;                           // 0x408(0x8)
	Class StaticMeshComponent*                                   cap_plinth_01_a;                                   // 0x410(0x8)
};


}