// Generated by DougTheDruid#2784 on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x4e94fa74
class BP_tls_speaking_trumpet_meg_01_a_ItemDesc_C: public ByteProperty
{
public:
	byte                                                         ;                                                  // 0x1d4(0x5f961)
};


}