// Generated by DougTheDruid#2784 on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x8
class BP_Trinket_WoodenBoat_01_a_C: public None
{
public:
	Class StaticMeshComponent*                                   None;                                              // 0x408(0x8)
};


}