// Generated by dougthedruid on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x8 (Full Size[0x408] - InheritedSize[0x400]
class BP_VFXStoryResponseManager_GoldenSands_C: public VfxStoryResponseManager
{
public:
	class SceneComponent*                                        DefaultSceneRoot;                                  // 0x400(0x8)
};


}