// Generated by dougthedruid on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x18 (Full Size[0xbe8] - InheritedSize[0xbd0]
class BP_wpn_sniper_rifle_smp_01_a_v03_Wieldable_C: public BP_EyeOfReach_C
{
public:
	class StaticMeshComponent*                                   shroud_fp;                                         // 0xbd0(0x8)
	class StaticMeshComponent*                                   shroudmask_tp;                                     // 0xbd8(0x8)
	class StaticMeshComponent*                                   shroud_tp;                                         // 0xbe0(0x8)
};


}