// Generated by dougthedruid on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x0 (Full Size[0x28] - InheritedSize[0x28]
class CompetitiveVoyagesServiceInterface: public Interface
{
public:
};


// Size 0x80 (Full Size[0x448] - InheritedSize[0x3c8]
class CompetitiveVoyagesService: public Actor
{
public:
	char                                                         pad0x38_BLQ2F[0x38];                               // 0x3c8(0x38)
	Class CompetitiveVoyagesServiceParams*                       ServiceParams;                                     // 0x400(0x8)
	char                                                         pad0x40_5N72Z[0x40];                               // 0x408(0x40)
};


// Size 0x8 (Full Size[0x30] - InheritedSize[0x28]
class CompetitiveVoyagesServiceParams: public DataAsset
{
public:
	Class VoyageDescDataAsset*                                   VoyageDesc;                                        // 0x28(0x8)
};


// Size 0x0 (Full Size[0x60] - InheritedSize[0x60]
class TaleQuestCompetitiveVoyagesService: public TaleQuestService
{
public:
};


// Size 0x0 (Full Size[0x28] - InheritedSize[0x28]
class TaleQuestCompetitiveVoyagesServiceDesc: public TaleQuestServiceDesc
{
public:
};


}