// Generated by DougTheDruid#2784 on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x0
class ContendedResourceInfoInterface: public Interface
{
public:
};


// Size 0x0
class ContendedResourceServiceInterface: public Interface
{
public:
};


// Size 0x0
class ReservableContendedResourceInterface: public Interface
{
public:
};


// Size 0x0
class WorldResourceRegistryInterface: public Interface
{
public:
};


}