#pragma once

// Generated by dougthedruid on Discord
// https://github.com/DougTheDruid

#include "CrewSkillRating_Structs.h"


// Size 0xf8 (Full Size[0x120] - InheritedSize[0x28]
class CrewSkillRatingService: public Object
{
public:
	char                                                         pad0xf8_2Q26N[0xf8];                               // 0x28(0xf8)
};


// Size 0x0 (Full Size[0x28] - InheritedSize[0x28]
class CrewSkillRatingServiceInterface: public Interface
{
public:
};


