#pragma once

// Generated by dougthedruid on Discord
// https://github.com/DougTheDruid

#include "CustomMeshComponent_Structs.h"


// Size 0x10 (Full Size[0x5c0] - InheritedSize[0x5b0]
class CustomMeshComponent: public MeshComponent
{
public:
	char                                                         pad0x10_F7GBT[0x10];                               // 0x5b0(0x10)
};


