#pragma once

// Generated by dougthedruid on Discord
// https://github.com/DougTheDruid

// Size 0x28 (Full Size[0x50] - InheritedSize[0x28]
class CustomItemService: public Object
{
public:
	char                                                         pad0x8_ESOQ5[0x8];                                 // 0x28(0x8)
	class World*                                                 World;                                             // 0x30(0x8)
	char                                                         pad0x18_NURW1[0x18];                               // 0x38(0x18)
};


// Size 0x0 (Full Size[0x28] - InheritedSize[0x28]
class CustomItemServiceInterface: public Interface
{
public:
};


