#pragma once

// Generated by dougthedruid on Discord
// https://github.com/DougTheDruid

#include "HarpoonFramework_Structs.h"


// Size 0x0 (Full Size[0x28] - InheritedSize[0x28]
class PortableHarpoonQueriableInterface: public Interface
{
public:
};


// Size 0x0 (Full Size[0x28] - InheritedSize[0x28]
class HarpoonDropItemInterface: public Interface
{
public:
};


