// Generated by dougthedruid on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x0 (Full Size[0x28] - InheritedSize[0x28]
class ItemQualityInterface: public Interface
{
public:
};


// Size 0x48 (Full Size[0x110] - InheritedSize[0xc8]
class ItemQualityComponent: public ActorComponent
{
public:
	char                                                         pad0x8_UK7I6[0x8];                                 // 0xc8(0x8)
	byte                                                         ItemQualityLevel;                                  // 0xd0(0x1)
	char                                                         pad0x7_RW22M[0x7];                                 // 0xd1(0x7)
	TArray<struct PerComanyItemQualityEntry>                     CompanySpecificItemQualityLevels;                  // 0xd8(0x10)
	TArray<struct PerComanyComplexItemQualityEntry>              CompanySpecificComplexItemQualityLevels;           // 0xe8(0x10)
	TArray<struct PerComanyComplexItemQualityEntry>              CompanySpecificComplexItemQualityLevelsHandin;     // 0xf8(0x10)
	class GuildSettings*                                         GuildSettings;                                     // 0x108(0x8)
};


}