// Generated by dougthedruid on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x20
struct KnockbackableInfo
{
public:
	char                                                         pad0x20_DOA4F[0x20];                               // 0x0(0x20)
};


}