#pragma once

// Generated by dougthedruid on Discord
// https://github.com/DougTheDruid

// Size 0x2c
struct NavalBattleShipData
{
public:
	char                                                         pad0x2c_PTE38[0x2c];                               // 0x0(0x2c)
};


