#pragma once

// Generated by dougthedruid on Discord
// https://github.com/DougTheDruid

// Size 0x150
struct NavalBattleShipData
{
public:
	char                                                         pad0x150_K9RM4[0x150];                             // 0x0(0x150)
};


