// Generated by dougthedruid on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0xa0
struct ObjectMessagingDispatcher
{
public:
	char                                                         pad0xa0_ZZ5P1[0xa0];                               // 0x0(0xa0)
};


// Size 0x8
struct ObjectMessagingDispatcherHandle
{
public:
	char                                                         pad0x8_I1K8J[0x8];                                 // 0x0(0x8)
};


// Size 0x58
struct ObjectMessagingHandle
{
public:
	char                                                         pad0x8_UQTEN[0x8];                                 // 0x0(0x8)
	class Struct*                                                EventType;                                         // 0x8(0x8)
	char                                                         pad0x48_NNCIH[0x48];                               // 0x10(0x48)
};


// Size 0x50
struct ObjectMessagingObjectScoper
{
public:
	char                                                         pad0x50_D98QK[0x50];                               // 0x0(0x50)
};


// Size 0x8
struct EventObjectMessagingDispatcherBeingDestroyed
{
public:
	char                                                         pad0x8_WSKSY[0x8];                                 // 0x0(0x8)
};


}