#pragma once

// Generated by dougthedruid on Discord
// https://github.com/DougTheDruid

// Size 0x10 (Full Size[0x48] - InheritedSize[0x38]
class SaferSeasSettings: public DeveloperSettings
{
public:
	struct StringAssetReference                                  SaferSeasBlacklistAsset;                           // 0x38(0x10)
};


// Size 0x28 (Full Size[0x3f0] - InheritedSize[0x3c8]
class SaferSeasDataAssetProviderService: public Actor
{
public:
	class SaferSeasEntitlementBlacklistDataAsset*                SaferSeasEntitlementBlacklistDataAsset;            // 0x3d0(0x8)
};


// Size 0x10 (Full Size[0x38] - InheritedSize[0x28]
class SaferSeasEntitlementBlacklistDataAsset: public DataAsset
{
public:
	TArray<Class>                                                BlacklistedEntitlements;                           // 0x28(0x10)
};


