// Generated by DougTheDruid#2784 on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x0
class BP_ShipTrinketMountpointManagerComponent_Large_C: public BP_ShipTrinketMountpointManagerComponent_C
{
public:
};


// Size 0x0
class BP_ShipTrinketMountpointManagerComponent_C: public ShipTrinketMountpointManagerComponent
{
public:
};


}