// Generated by dougthedruid on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x38 (Full Size[0x440] - InheritedSize[0x408]
class wld_palm_cluster_04_b_C: public BP_Placement_HeightDrop_C
{
public:
	class StaticMeshComponent*                                   wld_bush_03_a_02;                                  // 0x408(0x8)
	class StaticMeshComponent*                                   wld_bush_02_a_01;                                  // 0x410(0x8)
	class StaticMeshComponent*                                   wld_bush_03_a_01;                                  // 0x418(0x8)
	class StaticMeshComponent*                                   wld_tree_palm_01_a_01;                             // 0x420(0x8)
	class NonVagueNonUniqueLandmarkComponent*                    NonVagueNonUniqueLandmark;                         // 0x428(0x8)
	class StaticMeshComponent*                                   wld_tree_palm_02_b_01;                             // 0x430(0x8)
	class SceneComponent*                                        SharedRoot;                                        // 0x438(0x8)
};


}