// Generated by DougTheDruid#2784 on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x28 (Full Size[0x430] - InheritedSize[0x408]
class wld_palm_cluster_05_c_C: public BP_Placement_HeightDrop_C
{
public:
	Class StaticMeshComponent*                                   StaticMesh3;                                       // 0x408(0x8)
	Class StaticMeshComponent*                                   StaticMesh1;                                       // 0x410(0x8)
	Class NonVagueNonUniqueLandmarkComponent*                    NonVagueNonUniqueLandmark;                         // 0x418(0x8)
	Class StaticMeshComponent*                                   StaticMesh;                                        // 0x420(0x8)
	Class StaticMeshComponent*                                   StaticMesh2;                                       // 0x428(0x8)
};


}