// Generated by DougTheDruid#2784 on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x28 (Full Size[0x3f0] - InheritedSize[0x3c8]
class wsp_bottle_burner_a_C: public Actor
{
public:
	Class PointLightComponent*                                   None;                                              // 0x3c8(0x8)
	Class ParticleSystemComponent*                               None;                                              // 0x3d0(0x8)
	Class StaticMeshComponent*                                   None;                                              // 0x3d8(0x8)
	Class StaticMeshComponent*                                   None;                                              // 0x3e0(0x8)
	Class SceneComponent*                                        None;                                              // 0x3e8(0x8)
};


}