// Generated by dougthedruid on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x28 (Full Size[0x3f0] - InheritedSize[0x3c8]
class wsp_bottle_burner_a_C: public Actor
{
public:
	Class PointLightComponent*                                   PointLight;                                        // 0x3c8(0x8)
	Class ParticleSystemComponent*                               ParticleSystem;                                    // 0x3d0(0x8)
	Class StaticMeshComponent*                                   StaticMeshComponent01;                             // 0x3d8(0x8)
	Class StaticMeshComponent*                                   StaticMeshComponent0;                              // 0x3e0(0x8)
	Class SceneComponent*                                        SharedRoot;                                        // 0x3e8(0x8)
};


}