#pragma once

// Generated by dougthedruid on Discord
// https://github.com/DougTheDruid

// Size 0x48
struct ZoomedInOnWieldableItemActionStateConstructionInfo
{
public:
	float                                                        ZoomedInFov;                                       // 0x30(0x4)
	float                                                        FreelookPitch;                                     // 0x34(0x4)
	float                                                        FreelookYaw;                                       // 0x38(0x4)
	float                                                        FreelookOutInterpolationRate;                      // 0x3c(0x4)
	float                                                        LookSensitivityScaler;                             // 0x40(0x4)
};


