AutoCompleteCommand:
  Attributes:
  - Name: Command
    Offset: '0x0'
    Size: '0x10'
    Type: Struct FString
  - Name: Desc
    Offset: '0x10'
    Size: '0x10'
    Type: Struct FString
  - Name: Keywords
    Offset: '0x20'
    Size: '0x10'
    Type: Struct FString
  ClassSize: '0x30'
