MaterialShaderQualitySettings:
  Attributes: []
  ClassSize: '0x58'
  FullSize: '0x80'
  InheritedSize: '0x28'
  Super: Object
ShaderPlatformQualitySettings:
  Attributes:
  - Name: QualityOverrides
    Offset: '0x28'
    Size: '0x4'
    Type: Struct MaterialQualityOverrides
  ClassSize: '0x10'
  FullSize: '0x38'
  InheritedSize: '0x28'
  Super: Object
