#pragma once

// Name: SoT, Version: 2.3.0


/*!!DEFINE!!*/

/*!!HELPER_DEF!!*/

/*!!HELPER_INC!!*/

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace CG
{
//---------------------------------------------------------------------------
// Parameters
//---------------------------------------------------------------------------

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.PlayItemAnimation
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_PlayItemAnimation_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPC_ReapersBones_Skeleton_InCage_AnimGraphNode_TransitionResult_2A19BABE441DD3A8A797A89DBDCEDAA4
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPC_ReapersBones_Skeleton_InCage_AnimGraphNode_TransitionResult_2A19BABE441DD3A8A797A89DBDCEDAA4_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPC_ReapersBones_Skeleton_InCage_AnimGraphNode_TransitionResult_06441C554627078856052B91835CA919
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPC_ReapersBones_Skeleton_InCage_AnimGraphNode_TransitionResult_06441C554627078856052B91835CA919_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPC_ReapersBones_Skeleton_InCage_AnimGraphNode_TransitionResult_6FDC2D284DFBD56A28F530872CE00E36
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPC_ReapersBones_Skeleton_InCage_AnimGraphNode_TransitionResult_6FDC2D284DFBD56A28F530872CE00E36_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPC_ReapersBones_Skeleton_InCage_AnimGraphNode_TransitionResult_D37C932C42DD5D36F58926AAF4013D68
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPC_ReapersBones_Skeleton_InCage_AnimGraphNode_TransitionResult_D37C932C42DD5D36F58926AAF4013D68_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPC_ReapersBones_Skeleton_InCage_AnimGraphNode_TransitionResult_CB0BEC1F4FE866352673FA9E1D736D8A
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPC_ReapersBones_Skeleton_InCage_AnimGraphNode_TransitionResult_CB0BEC1F4FE866352673FA9E1D736D8A_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPC_ReapersBones_Skeleton_InCage_AnimGraphNode_TransitionResult_F218C5CD406D08FDF06139960ED433FB
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPC_ReapersBones_Skeleton_InCage_AnimGraphNode_TransitionResult_F218C5CD406D08FDF06139960ED433FB_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPC_ReapersBones_Skeleton_InCage_AnimGraphNode_TransitionResult_1777D02445DF620F5644A4AE9244283E
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPC_ReapersBones_Skeleton_InCage_AnimGraphNode_TransitionResult_1777D02445DF620F5644A4AE9244283E_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPC_ReapersBones_Skeleton_InCage_AnimGraphNode_TransitionResult_9D1C567C49CA7C2997D16A92AEC95F96
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPC_ReapersBones_Skeleton_InCage_AnimGraphNode_TransitionResult_9D1C567C49CA7C2997D16A92AEC95F96_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPC_ReapersBones_Skeleton_InCage_AnimGraphNode_TransitionResult_2BF3E127400369FDF04DCBA40242B051
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPC_ReapersBones_Skeleton_InCage_AnimGraphNode_TransitionResult_2BF3E127400369FDF04DCBA40242B051_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPC_ReapersBones_Skeleton_InCage_AnimGraphNode_TransitionResult_05C84FA84FEE4E47B3142DB9435A4073
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPC_ReapersBones_Skeleton_InCage_AnimGraphNode_TransitionResult_05C84FA84FEE4E47B3142DB9435A4073_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPC_ReapersBones_Skeleton_InCage_AnimGraphNode_TransitionResult_641261A0483D88B4E98E1688F7168816
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPC_ReapersBones_Skeleton_InCage_AnimGraphNode_TransitionResult_641261A0483D88B4E98E1688F7168816_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPC_ReapersBones_Skeleton_InCage_AnimGraphNode_TransitionResult_013BF8874E9530826F3A2BA7C4A69C3F
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPC_ReapersBones_Skeleton_InCage_AnimGraphNode_TransitionResult_013BF8874E9530826F3A2BA7C4A69C3F_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_StartLookat
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_StartLookat_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_StopLookAt
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_StopLookAt_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_IdleVariantChange
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_IdleVariantChange_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_InactiveVariantChange
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_InactiveVariantChange_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_InteractVariantChange
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_InteractVariantChange_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.BlueprintInitializeAnimation
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_BlueprintInitializeAnimation_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_NPCLookAtOn
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_NPCLookAtOn_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_NPCLookAtOff
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_NPCLookAtOff_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_EnteredNull
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_EnteredNull_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_EnteredOneShot
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_EnteredOneShot_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_EnteredContinuousOut
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_EnteredContinuousOut_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_EnteredContinuousLoopB
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_EnteredContinuousLoopB_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_EnteredContinuousLoopA
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_EnteredContinuousLoopA_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_EnteredContinuousIn
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_EnteredContinuousIn_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_NPCSelectNewCustomAnim_B
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_NPCSelectNewCustomAnim_B_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_NPCSelectNewCustomAnim_A
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_NPCSelectNewCustomAnim_A_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_NPCDeactivateCustomAnimSequence
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_NPCDeactivateCustomAnimSequence_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_RH_DetachSocketB
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_RH_DetachSocketB_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_LH_DetachSocketB
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_LH_DetachSocketB_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_RH_DetachSocketA
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_RH_DetachSocketA_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_LH_DetachSocketA
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_LH_DetachSocketA_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_LH_UseItem_11
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_LH_UseItem_11_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_LH_UseItem_10
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_LH_UseItem_10_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_LH_UseItem_9
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_LH_UseItem_9_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_LH_UseItem_8
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_LH_UseItem_8_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_LH_UseItem_7
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_LH_UseItem_7_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_LH_UseItem_6
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_LH_UseItem_6_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_RH_UseItem_11
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_RH_UseItem_11_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_RH_UseItem_10
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_RH_UseItem_10_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_RH_UseItem_9
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_RH_UseItem_9_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_RH_UseItem_8
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_RH_UseItem_8_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_RH_UseItem_7
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_RH_UseItem_7_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_RH_UseItem_6
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_RH_UseItem_6_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_RH_AttachItem
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_RH_AttachItem_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_LH_AttachItem
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_LH_AttachItem_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_LH_DetachItem
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_LH_DetachItem_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_RH_DetachItem
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_RH_DetachItem_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_RH_DestroyItem
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_RH_DestroyItem_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_RH_UseItem_5
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_RH_UseItem_5_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_RH_UseItem_4
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_RH_UseItem_4_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_RH_UseItem_3
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_RH_UseItem_3_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_RH_UseItem_2
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_RH_UseItem_2_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_LH_DestroyItem
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_LH_DestroyItem_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_LH_UseItem_5
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_LH_UseItem_5_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_LH_UseItem_4
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_LH_UseItem_4_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_LH_UseItem_3
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_LH_UseItem_3_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.AnimNotify_LH_UseItem_2
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_AnimNotify_LH_UseItem_2_Params
{
};

// Function BP_Anim_NPC_ReapersBones_Skeleton_InCage.BP_Anim_NPC_ReapersBones_Skeleton_InCage_C.ExecuteUbergraph_BP_Anim_NPC_ReapersBones_Skeleton_InCage
struct UBP_Anim_NPC_ReapersBones_Skeleton_InCage_C_ExecuteUbergraph_BP_Anim_NPC_ReapersBones_Skeleton_InCage_Params
{
	int                                                EntryPoint;                                                // 0x0000(0x0004)  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
