// Generated by DougTheDruid#2784 on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x0
class BP_Earthquake_Feature_C: public None
{
public:
};


// Size 0x0
class BP_Earthquake_C: public Earthquake
{
public:
};


}