// Generated by DougTheDruid#2784 on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x58
class BP_ItemPreview_Lighting_C: public Actor
{
public:
	Class ExponentialHeightFogComponent*                         None;                                              // 0x3d0(0x8)
	Class SkyLightComponent*                                     None;                                              // 0x3d8(0x8)
	Class SpotLightComponent*                                    None;                                              // 0x3e0(0x8)
	Class SpotLightComponent*                                    None;                                              // 0x3e8(0x8)
	Class SpotLightComponent*                                    None;                                              // 0x3f0(0x8)
	Class PostProcessComponent*                                  None;                                              // 0x3f8(0x8)
	Class SceneComponent*                                        None;                                              // 0x400(0x8)
};


}