// Generated by DougTheDruid#2784 on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x0
class BP_male_head_stubble_01_Desc_C: public ClothingDesc
{
public:
};


// Size 0x0
class BP_male_head_stubble_02_Desc_C: public ClothingDesc
{
public:
};


// Size 0x0
class BP_male_head_stubble_03_Desc_C: public ClothingDesc
{
public:
};


}