// Generated by DougTheDruid#2784 on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x40
class BP_Placement_HeightDrop_C: public Actor
{
public:
	Class SceneComponent*                                        None;                                              // 0x3d0(0x8)
	bool                                                         None;                                              // 0x3d8(0x1)
};


}