// Generated by DougTheDruid#2784 on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x18
class BP_SmallShip_WindowHatch_C: public SwitchMechanismTrigger
{
public:
	Struct PointerToUberGraphFrame                               UberGraphFrame;                                    // 0x560(0x8)
	Class StaticMeshComponent*                                   shp_mid_serving_hatch_R_01_a;                      // 0x568(0x8)
	Class InteractableComponent*                                 Interactable;                                      // 0x570(0x8)
};


}