// Generated by DougTheDruid#2784 on Discord
// https://github.com/DougTheDruid
namespace DougsSDKDumper
{
//-----
// Classes
//-----

// Size 0x8
class BP_GiveShroudbreaker_Shroudbreaker_C: public Actor
{
public:
	Class StaticMeshComponent*                                   gmp_tal_shroudbreaker_statue_01_a;                 // 0x3d0(0x8)
};


}